language: php

php:
  - 5.2
  - 5.3
  - 5.4

env:
 - WP_VERSION=3.4.1 WP_MULTISITE=0
 - WP_VERSION=3.4.1 WP_MULTISITE=1

before_install:
  - git clone https://github.com/sebastianbergmann/php-test-helpers.git
  - cd php-test-helpers
  - phpize && ./configure && make && make install
  - cd ../
  - export JPHP_INI=`php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - export JXDB=`php --ini | grep "xdebug" | sed -e "s/.*:\s*//" -e "s/,.*//"`
  - if [ $JXDB -a -f $JXDB ]; then sed -i='' -e "s/^/;/g" $JXDB; fi
  - if [[ ! `cat $JPHP_INI | grep 'test_helpers.so'` ]]; then echo "extension=test_helpers.so" >> $JPHP_INI; fi

before_script:
  - wget https://raw.github.com/johnpbloch/wordpress-plugin-tests/setup/setup.sh
  - sh setup.sh
  - cd ../tests

script: phpunit -c phpunit.xml All
